### PR TITLE
Feature/pass config

### PR DESCRIPTION
**Pull request by kaiomagalhaes**
#13 

@ThomasBush
@codelitt 
@Lockyy 
@seathony

### CODE REVIEW

**Comment by codelitt** [comment]
Haha let's make the message from the dog a little less intense. It is a
pretty strong phrase in English. Maybe like "Let's play fetch".

**Comment by kaiomagalhaes** [comment]
@codelitt Done, I was just thinking in one of my dogs when I wrote... :grin:

**Comment by codelitt** [comment]
:+1: LGTM to merge

**Comment by kaiomagalhaes** [comment]
@codelitt as soon as you do the merge I will generate the new version.

**Comment by codelitt** [comment]
Merged! Thanks everyone

**Comment by ThomasBush** [comment]
Very cool, thanks so much @kaiomagalhaes  @codelitt!

**Pull request merged**
