### PR TITLE
it was in singleton slack_notifier

### PR DESCRIPTION
**Pull request by tamai**
hello :smiley: 

Though are using slack_notifier,
I thought that there is better to a singleton, I tried to fix.

### CODE REVIEW

**Comment by kaiomagalhaes** [comment]
@tamai Thanks for you contribution!
@codelitt @Lockyy  what do you guys think? My only concern is that I was thinking in being able to pass the webhook in the config too so an application could send a message for more than one channel.

**Comment by Lockyy** [comment]
Could make it keep multiple and then look up by webhook. Then you can still pass the webhook in whilst gaining the benefit of not creating a Slack::Notifier every time.

**Comment by kaiomagalhaes** [comment]
@Lockyy Do you mean by creating a hash of instances which keys are the webhook?

**Comment by Lockyy** [comment]
Yeah, that'd be the simplest way to do it.

**Comment by kaiomagalhaes** [comment]
@Lockyy for me we can merge and create a issue to allow mode than one webhook with this solution, what do you think?

**Comment by Lockyy** [comment]
The issue is that doing that reduces the current functionality.

**Comment by kaiomagalhaes** [comment]
Why it would reduce the current functionality?

**Comment by Lockyy** [comment]
Right now you can use multiple webhooks, with this you wouldn't be able to.

**Comment by kaiomagalhaes** [comment]
yea... but to do it he has to change the env variable, but it works. Yeah
you are right

**Comment by kaiomagalhaes** [comment]
@tamai I will close this PR until we implement an option to use multiples webhooks. Feel free to implement it or I will do it as soon as possible

@tamai Thanks for your contribution

**Comment by tamai** [comment]
@kaiomagalhaes 
I'm sorry. Is delayed reply.
Thank you to discuss issue.
I found the direction that you want to do.
Come to think of it I also.

**Pull request closed without merging**
